SebastianNiemann/Mantella

CMakeLists.txt, include/mantella_bits/optimisationAlgorithm/samplingBasedOptimisationAlgorithm/randomSearch.hpp, test/optimisationAlgorithm/samplingBasedOptimisationAlgorithm/randomSearch.cpp
Tests for RandomSearch.
Signed-off-by: Daniel Kiechle kiechle@sra.uni-hannover.de.
=> Add tests for random search

src/optimisationProblem.cpp
Pretty sure one OptimisationProblem:: is enough ;)
=> double the problem

test/testOptimisationAlgorithm.cpp
see title, just some changes to be able to build this
=> enabling this to be buildable

src/optimisationAlgorithm/hookeJeevesAlgorithm.cpp
=> hotfix: Fixing the step size decrease in the Hooke-Jeeves algorithm

README.md
=> doc: Added the Gitter link under *Got a Problem or Question?* as a way to ask us directly.

include/mantella_bits/optimisationProblem.hpp, src/optimisationProblem.cpp, test/testOptimisationProblem.cpp
=> maintaince: Grouped the *minimalParameterDistance* together with the parameter space modifiers

Vagrantfile
=> maintaince: Cleaner debugging and testing separation within the Vagrantfile

src/assert.cpp
=> maintaince: Fixed typo (different -> differentiate)

CMakeLists.txt
=> maintaince: Reduced the required CMake version number to 2.8.7

include/mantella_bits/optimisationAlgorithm.hpp, src/optimisationAlgorithm.cpp
=> maintaince: Replaced stagnationDetection by isStagnating

.setup.sh, .travis.yml, Vagrantfile
=> maintaince: Increased Vagrantfile verbosity

test/testOptimisationProblem.cpp
=> fix: Fixed occasional rounding error in tests

.gitattributes
=> maintaince: Setup .gitattributes to perform LF normalization

test/testOptimisationAlgorithm.cpp
=> maintaince: Replaced bounaries handling by bounaries-handling

include/mantella_bits/optimisationProblem/kinematicallyRedundantMachines/parallelKinematicMachine3PRPR.hpp, include/mantella_bits/optimisationProblem/kinematicallyRedundantMachines/parallelKinematicMachine3PRRR.hpp, include/mantella_bits/optimisationProblem/kinematicallyRedundantMachines/parallelKinematicMachine6PRUS.hpp, include/mantella_bits/optimisationProblem/kinematicallyRedundantMachines/parallelKinematicMachine6PUPS.hpp
=> refactor: Reduced internal robot parameter visibility

include/mantella_bits/optimisationAlgorithm.hpp, include/mantella_bits/optimisationAlgorithm/hillClimbing.hpp, include/mantella_bits/optimisationAlgorithm/hookeJeevesAlgorithm.hpp, include/mantella_bits/optimisationAlgorithm/particleSwarmOptimisation.hpp, include/mantella_bits/optimisationAlgorithm/simulatedAnnealing.hpp
=> refactoring: Increased the visibility of member varibales inside algorithms to be used in lambda functions

CONTRIBUTING.md
=> doc: Complete overhaul of the contribution guideline

test/testNumericalAnalysis.cpp
=> Fix: Unexcepted Brent exception

README.md
=> doc: Updated year and version number

CMakeLists.txt, include/mantella, include/mantella_bits/orbitalMechanics.hpp, src/orbitalMechanics.cpp, test/testOrbitalMechanics.cpp
=> feature: Added Stumpff function

include/mantella_bits/orbitalMechanics.hpp, src/orbitalMechanics.cpp, test/testOrbitalMechanics.cpp
=> feature: Added interplanetary time of flight function (based on Bate's universal variables)

include/mantella_bits/orbitalMechanics.hpp, src/orbitalMechanics.cpp, test/testOrbitalMechanics.cpp
=> feature: Added sphere of influence function

README.md, include/mantella
=> doc: Increaded version number and c++ version [ci skip]

test/catchHelper.cpp
=> test: Corrected bounds and reduced the confidence interval to 0.9

Dockerfile
=> feature: Adds alternative library path

LICENSE.txt
=> doc: Updated license year

README.md
=> doc: Fixed Mantella logo

.travis.yml
=> misc: Removed obsolete coveralls commands

.develop.sh
=> misc: Removed obsolete TODO

.gitignore
=> misc: added slash to directories

Dockerfile
=> misc: Removed LD_LIBRARY_PATH command

.travis.yml, CONTRIBUTING.md, test/CMakeLists.txt
=> test: Using the local include folder instead of the installed one

include/mantella_bits/analyse.hpp, include/mantella_bits/evaluate.hpp, include/mantella_bits/optimisation_algorithm.hpp, include/mantella_bits/optimisation_algorithm/hill_climbing.hpp, include/mantella_bits/optimisation_algorithm/hooke_jeeves_algorithm.hpp, include/mantella_bits/optimisation_algorithm/particle_swarm_optimisation.hpp, include/mantella_bits/optimisation_algorithm/random_search.hpp, include/mantella_bits/optimisation_problem.hpp, include/mantella_bits/optimisation_problem/ackley_function.hpp, include/mantella_bits/optimisation_problem/rastrigin_function.hpp, include/mantella_bits/optimisation_problem/rosenbrock_function.hpp, include/mantella_bits/optimisation_problem/sphere_function.hpp, include/mantella_bits/optimisation_problem/sum_of_different_powers_function.hpp, include/mantella_bits/optimise.hpp, include/mantella_bits/property_analysis/additive_separability.hpp, include/mantella_bits/randomisation/random_neighbour.hpp
=> devel: Removed unused pragma once

include/mantella_bits/optimisation_algorithm.hpp, include/mantella_bits/optimisation_algorithm/hill_climbing.hpp, include/mantella_bits/optimisation_algorithm/hooke_jeeves_algorithm.hpp, include/mantella_bits/optimisation_algorithm/particle_swarm_optimisation.hpp, include/mantella_bits/optimisation_algorithm/random_search.hpp
=> develop: Simpler function names

include/mantella0_bits/optimisation_algorithm.hpp, include/mantella0_bits/optimisation_algorithm/particle_swarm_optimisation.hpp
=> fix: Fixes PSO attraction_center calculation

include/mantella0_bits/optimisation_algorithm.hpp
=> develop: Removed unnecessary this

.travis.yml, include/mantella0_bits/optimisation_algorithm/particle_swarm_optimisation.hpp, include/mantella0_bits/optimise.hpp
=> test: Added osx to the test matrix

appveyor.yml
=> test: Unified string handling

Dockerfile
=> develop: Removed obsolete compiler alternatives

README.md
=> doc: Updated example

README.md
=> doc: Removed the link to our api documentation for now

include/mantella0_bits/optimise.hpp
=> feature: Added optimise overloads

include/mantella0_bits/optimiser/particle_swarm_optimisation.hpp
=> test: Using more than one initial parameter

README.md
Previous code example can't be compiled. I just changes a few lines.
=> Fix README.md code example

README.md
=> doc: Small style update

.gitignore
=> develop: Minor style fix

include/mantella0, include/mantella0_bits/optimise.hpp, include/mantella0_bits/optimiser.hpp, include/mantella0_bits/optimiser/hill_climbing.hpp, include/mantella0_bits/optimiser/hooke_jeeves_algorithm.hpp, include/mantella0_bits/optimiser/nelder_mead_method.hpp, include/mantella0_bits/optimiser/particle_swarm_optimisation.hpp, include/mantella0_bits/optimiser/random_search.hpp
=> feature: Added time-based stopping criteria

README.md
=> doc: Show the master branch's build status for AppVeyor's badge

README.md
=> doc: Minor code example specification

include/mantella0_bits/optimise.hpp, include/mantella0_bits/problem/ackley_function.hpp, include/mantella0_bits/problem/rastrigin_function.hpp, include/mantella0_bits/problem/rosenbrock_function.hpp, include/mantella0_bits/problem/sphere_function.hpp, include/mantella0_bits/problem/sum_of_different_powers_function.hpp
=> develop: Transformed the bounds to [0, 1].

include/mantella0_bits/optimise.hpp, include/mantella0_bits/optimiser/hill_climbing.hpp, include/mantella0_bits/optimiser/hooke_jeeves_algorithm.hpp, include/mantella0_bits/optimiser/nelder_mead_method.hpp, include/mantella0_bits/optimiser/particle_swarm_optimisation.hpp, include/mantella0_bits/optimiser/random_search.hpp, include/mantella0_bits/problem/sphere_function.hpp
=> fix: The best parameter should remain within bounds.

include/mantella0_bits/optimise.hpp, include/mantella0_bits/optimiser.hpp, include/mantella0_bits/optimiser/hill_climbing.hpp, include/mantella0_bits/optimiser/hooke_jeeves_algorithm.hpp, include/mantella0_bits/optimiser/nelder_mead_method.hpp, include/mantella0_bits/optimiser/particle_swarm_optimisation.hpp, include/mantella0_bits/optimiser/random_search.hpp
=> feature: Chooses the number of initial parameters optimiser-dependet

README.md
=> doc: Added installation instructions

include/mantella0_bits/optimiser/hill_climbing.hpp, include/mantella0_bits/optimiser/hooke_jeeves_algorithm.hpp, include/mantella0_bits/optimiser/nelder_mead_method.hpp, include/mantella0_bits/optimiser/particle_swarm_optimisation.hpp, include/mantella0_bits/optimiser/random_search.hpp
=> test: Added tests for stopping criteria

README.md
=> doc: Updated Coverity Scan badge url

README.md
=> doc: Updated readme

doc/_themes/mantella/layout.html, doc/_themes/mantella/static/style.css, include/mantella0_bits/problem.hpp
=> feature: Added MathJax support

doc/_themes/mantella/static/style.css, doc/conf.py, doc/index.rst, include/mantella0_bits/problem.hpp
=> doc: Added mant::problem api documentation

.travis.yml
=> fix: Fixes broken builds because of Travis recent Xcode upgrade

doc/_themes/mantella/static/style.css
=> doc: Limited the maximal width

CONTRIBUTING.md, README.md, doc/_themes/mantella/layout.html, doc/_themes/mantella/static/style.css
=> develop: Fixed several coding styles

Dockerfile
=> develop: Simplified Dockerfile

doc/.pre_processing.py
=> fix: Removed the duplicated :widths: addition

doc/.pre_processing.py
=> doc: Adjusted changelog indentation

doc/.pre_processing.py, doc/_themes/mantella/static/style.css
=> Add language labels to code blocks in the documentation

doc/.pre_processing.py
=> Align doc/.pre_processing.py with Mantella style guide

README.md
=> doc: Fixed the Windows/AppVeyor badge

doc/index.rst, include/mantella0, include/mantella0_bits/evaluate.hpp, include/mantella0_bits/optimise.hpp
=> Implement `mant::evaluate()`

Dockerfile
=> Added tinkerer to docker file

doc/conf.py
=> Add tinkerer as sphinx extension

doc/.pre_processing.py
=> doc: Overwrite animations without stopping the build script

benchmark/benchmark.m
=> benchmark: Makes sure that all benchmark plots have the same y axis limits

Dockerfile, doc/conf.py
=> Fix: Deploying on travis for gh-pages

include/mantella0_bits/evaluate.hpp
=> Updated headline at evaluate.hpp

README.md
=> doc: Updated year

include/mantella0
=> doc: Added Oskar Pusz as maintainer
